In [3]:
import pandas as pd

bouts = pd.read_csv("ufc_combined_1008.csv", index_col = 0)

In [4]:
bouts.head()

,Winner,Event,Date,Location,Fighter 1,Fighter 2,Weight class,Stance 1,Career W 1,Career L 1,...,Time Avg 2,Streak 2,Career W 2,Career L 2,Career Fights 2,Career W Perc 2,Ht Diff 2,Reach Diff 2,Age 2,Stance 2
0,1,The Ultimate Fighter: A Champion Will Be Crown...,2014-12-12 00:00:00,"Las Vegas, Nevada, USA",Joanne Wood,Seo Hee Ham,Women's Strawweight,Orthodox,8,0,...,0.00,0.0,16,5,21.0,76.190476,-4.0,-3.0,27.0,Southpaw
1,0,UFC Fight Night: Gonzaga vs Cro Cop 2,2015-04-11 00:00:00,"Krakow, Poland",Joanne Wood,Maryna Moroz,Women's Strawweight,Orthodox,9,0,...,0.00,0.0,5,0,5.0,100.000000,1.0,2.0,24.0,Orthodox
2,0,UFC Fight Night: Bisping vs Leites,2015-07-18 00:00:00,"Glasgow, Scotland, United Kingdom",Cortney Casey,Joanne Wood,Women's Strawweight,Orthodox,4,1,...,495.00,-1.0,9,1,10.0,90.000000,-1.0,-2.0,30.0,Orthodox
3,1,UFC Fight Night: MacDonald vs Thompson,2016-06-18 00:00:00,"Ottawa, Ontario, Canada",Joanne Wood,Valerie Letourneau,Women's Flyweight,Orthodox,10,1,...,1050.00,-1.0,8,4,12.0,66.666667,1.0,3.0,33.0,Orthodox
4,0,UFC 203: Miocic vs. Overeem,2016-09-10 00:00:00,"Cleveland, Ohio, USA",Joanne Wood,Jessica Andrade,Women's Strawweight,Orthodox,11,1,...,587.25,1.0,14,5,19.0,73.684211,-5.0,-3.0,25.0,Orthodox

In [22]:
bouts.columns

Index(['Winner', 'Event', 'Date', 'Location', 'Fighter 1', 'Fighter 2',
       'Weight class', 'Stance 1', 'Career W 1', 'Career L 1', 'W 1', 'L 1',
       'Num Fights 1', 'W Perc 1', 'Sig Strikes Avg 1', 'Sig Str % 1',
       'Sig Strikes Opp Avg 1', 'Sig Str % Opp 1', 'Strikes Avg 1', 'Str % 1',
       'Strikes Opp Avg 1', 'Str % Opp 1', 'TD Avg 1', 'TD % 1',
       'TD Opp Avg 1', 'TD % Opp 1', 'KD Avg 1', 'KD Opp Avg 1', 'KO Avg 1',
       'SUB Avg 1', 'KO Opp Avg 1', 'SUB Opp Avg 1', 'CTRL Avg 1',
       'CTRL Opp Avg 1', 'Time Avg 1', 'Streak 1', 'Ht Diff 1', 'Reach Diff 1',
       'Age 1', 'Career Fights 1', 'Career W Perc 1', 'W 2', 'L 2',
       'Num Fights 2', 'W Perc 2', 'Sig Strikes Avg 2', 'Sig Str % 2',
       'Sig Strikes Opp Avg 2', 'Sig Str % Opp 2', 'Strikes Avg 2', 'Str % 2',
       'Strikes Opp Avg 2', 'Str % Opp 2', 'TD Avg 2', 'TD % 2',
       'TD Opp Avg 2', 'TD % Opp 2', 'KD Avg 2', 'KD Opp Avg 2', 'KO Avg 2',
       'SUB Avg 2', 'KO Opp Avg 2', 'SUB Opp Avg 2', 'CTRL Avg 2',
       'CTRL Opp Avg 2', 'Time Avg 2', 'Streak 2', 'Career W 2', 'Career L 2',
       'Career Fights 2', 'Career W Perc 2', 'Ht Diff 2', 'Reach Diff 2',
       'Age 2', 'Stance 2'],
      dtype='object')

In [14]:
bouts_check = bouts[(bouts['Fighter 1'] == 'Dustin Poirier') | (bouts['Fighter 2'] == 'Dustin Poirier')]
# bouts_check = bouts[(bouts['Fighter 1'] == 'Islam Makhachev') | (bouts['Fighter 2'] == 'Dustin Poirier')]

In [39]:
bouts_error = bouts[(bouts['Career L 1'] < 0) | (bouts['Career L 2'] < 0)]
# bouts_error = bouts[(bouts['L 1'] < 0) | (bouts['L 2'] < 0)]

In [40]:
bouts_error

Empty DataFrame
Columns: [Winner, Event, Date, Location, Fighter 1, Fighter 2, Weight class, Stance 1, Career W 1, Career L 1, W 1, L 1, Num Fights 1, W Perc 1, Sig Strikes Avg 1, Sig Str % 1, Sig Strikes Opp Avg 1, Sig Str % Opp 1, Strikes Avg 1, Str % 1, Strikes Opp Avg 1, Str % Opp 1, TD Avg 1, TD % 1, TD Opp Avg 1, TD % Opp 1, KD Avg 1, KD Opp Avg 1, KO Avg 1, SUB Avg 1, KO Opp Avg 1, SUB Opp Avg 1, CTRL Avg 1, CTRL Opp Avg 1, Time Avg 1, Streak 1, Ht Diff 1, Reach Diff 1, Age 1, Career Fights 1, Career W Perc 1, W 2, L 2, Num Fights 2, W Perc 2, Sig Strikes Avg 2, Sig Str % 2, Sig Strikes Opp Avg 2, Sig Str % Opp 2, Strikes Avg 2, Str % 2, Strikes Opp Avg 2, Str % Opp 2, TD Avg 2, TD % 2, TD Opp Avg 2, TD % Opp 2, KD Avg 2, KD Opp Avg 2, KO Avg 2, SUB Avg 2, KO Opp Avg 2, SUB Opp Avg 2, CTRL Avg 2, CTRL Opp Avg 2, Time Avg 2, Streak 2, Career W 2, Career L 2, Career Fights 2, Career W Perc 2, Ht Diff 2, Reach Diff 2, Age 2, Stance 2]
Index: []

[0 rows x 75 columns]

In [45]:
bouts_check = bouts[(bouts['Fighter 1'] == 'Cesar Almeida') | (bouts['Fighter 2'] == 'Cesar Almeida')]
# bouts_check = bouts[(bouts['Fighter 1'] == 'Dustin Poirier') | (bouts['Fighter 2'] == 'Dustin Poirier')]

In [46]:
bouts_check

,Winner,Event,Date,Location,Fighter 1,Fighter 2,Weight class,Stance 1,Career W 1,Career L 1,...,Time Avg 2,Streak 2,Career W 2,Career L 2,Career Fights 2,Career W Perc 2,Ht Diff 2,Reach Diff 2,Age 2,Stance 2
111,1,UFC 302: Makhachev vs. Poirier,2024-06-01 00:00:00,"Newark, New Jersey, USA",Roman Kopylov,Cesar Almeida,Middleweight,Southpaw,12,3,...,433.0,1.0,5,-1,4.0,125.000000,1.0,-1.0,36.0,Orthodox
305,0,UFC Fight Night: Allen vs. Curtis 2,2024-04-06 00:00:00,"Las Vegas, Nevada, USA",Dylan Budka,Cesar Almeida,Middleweight,Switch,7,2,...,0.0,0.0,4,-1,3.0,133.333333,1.0,-1.0,36.0,Orthodox
306,0,UFC 307: Pereira vs. Rountree Jr.,2024-10-05 00:00:00,"Salt Lake City, Utah, USA",Ihor Potieria,Cesar Almeida,Middleweight,Southpaw,20,5,...,666.5,-1.0,5,0,5.0,100.000000,-2.0,-1.0,36.0,Orthodox

In [41]:
CesarAlmeida = pd.read_csv("CesarAlmeida_new_stats.csv", index_col = 0)

In [42]:
CesarAlmeida

,Unnamed: 0,Event,Date,Location,W/L 1,Fighter 1,Fighter 2,Weight class,Stance,Career W,...,SUB Opp Avg,CTRL Avg,CTRL Opp Avg,Time Avg,Streak,Ht Diff,Reach Diff,Age,Career Fights,Career W Perc
0,33,UFC Fight Night: Allen vs. Curtis 2,2024-04-06,"Las Vegas, Nevada, USA",win,Cesar Almeida,Dylan Budka,Middleweight,Orthodox,4,...,0.0,0.0,0.0,0.0,0.0,1.0,-1.0,36.0,4.0,100.000000
1,16,UFC 302: Makhachev vs. Poirier,2024-06-01,"Newark, New Jersey, USA",NaN,Cesar Almeida,Roman Kopylov,Middleweight,Orthodox,5,...,0.0,353.0,12.0,433.0,1.0,1.0,-1.0,36.0,5.0,100.000000
2,7836,UFC 307: Pereira vs. Rountree Jr.,2024-10-05,"Salt Lake City, Utah, USA",NaN,Cesar Almeida,Ihor Potieria,Middleweight,Orthodox,5,...,0.0,436.0,6.0,666.5,-1.0,-2.0,-1.0,36.0,6.0,83.333333

In [43]:
CesarAlmeida['L']

0    0.0
1    0.0
2    1.0
Name: L, dtype: float64

In [44]:
CesarAlmeida['Career L']

0    0
1    0
2    1
Name: Career L, dtype: int64

In [21]:
# for col in valter.columns:
#     print(valter[col])

0      39
1    7670
Name: Unnamed: 0, dtype: int64
0    UFC Fight Night: Allen vs. Curtis 2
1       UFC 305: Du Plessis vs. Adesanya
Name: Event, dtype: object
0    2024-04-06
1    2024-08-17
Name: Date, dtype: object
0                 Las Vegas, Nevada, USA
1    Perth, Western Australia, Australia
Name: Location, dtype: object
0    NaN
1    win
Name: W/L 1, dtype: object
0    Valter Walker
1    Valter Walker
Name: Fighter 1, dtype: object
0    Lukasz Brzeski
1       Junior Tafa
Name: Fighter 2, dtype: object
0    Heavyweight
1    Heavyweight
Name: Weight class, dtype: object
0    Orthodox
1    Orthodox
Name: Stance, dtype: object
0    11
1    11
Name: Career W, dtype: int64
0    0
1    1
Name: Career L, dtype: int64
0    1997
1    1997
Name: born_year, dtype: int64
0    0.0
1    0.0
Name: W, dtype: float64
0    0.0
1    1.0
Name: L, dtype: float64
0    0.0
1    1.0
Name: Num Fights, dtype: float64
0    0.0
1    0.0
Name: W Perc, dtype: float64
0     0.0
1    58.0
Name: Sig Strikes Avg, dtype: float64
0     0.000000
1    56.862745
Name: Sig Str %, dtype: float64
0     0.0
1    33.0
Name: Sig Strikes Opp Avg, dtype: float64
0     0.000000
1    49.253731
Name: Sig Str % Opp, dtype: float64
0      0.0
1    135.0
Name: Strikes Avg, dtype: float64
0     0.000000
1    44.701987
Name: Str %, dtype: float64
0     0.0
1    56.0
Name: Strikes Opp Avg, dtype: float64
0     0.000000
1    33.333333
Name: Str % Opp, dtype: float64
0    0.0
1    0.0
Name: TD Avg, dtype: float64
0    0.0
1    0.0
Name: TD %, dtype: float64
0    0.0
1    4.0
Name: TD Opp Avg, dtype: float64
0     0.0
1    80.0
Name: TD % Opp, dtype: float64
0    0.0
1    0.0
Name: KD Avg, dtype: float64
0    0.0
1    0.0
Name: KD Opp Avg, dtype: float64
0    0.0
1    0.0
Name: KO Avg, dtype: float64
0    0.0
1    0.0
Name: SUB Avg, dtype: float64
0    0.0
1    0.0
Name: KO Opp Avg, dtype: float64
0    0.0
1    0.0
Name: SUB Opp Avg, dtype: float64
0     0.0
1    43.0
Name: CTRL Avg, dtype: float64
0      0.0
1    439.0
Name: CTRL Opp Avg, dtype: float64
0      0.0
1    900.0
Name: Time Avg, dtype: float64
0    0.0
1   -1.0
Name: Streak, dtype: float64
0    2.0
1    3.0
Name: Ht Diff, dtype: float64
0    0.0
1    3.0
Name: Reach Diff, dtype: float64
0    27.0
1    27.0
Name: Age, dtype: float64
0    11.0
1    12.0
Name: Career Fights, dtype: float64
0    100.000000
1     91.666667
Name: Career W Perc, dtype: float64